name: Comment on


on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed
  pull_request:
    types: [closed]
    branches:
      - main      
  
jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'  && github.event.pull_request.merged==true
    steps:
        - name: 'workflow_run.event'
          run: echo ${{  github.event.workflow_run.event }}
        - name: 'workflow_run.event'
          run: echo ${{   github.event.pull_request.merged }}
        - name: 'workflow_run'
          run: echo ${{ github.event.workflow_run }}
          
          
    
