name: Comment on PR

on:
  workflow_run:
    workflows: ["Receive PR"]
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.pull_requests[0].merged == true
    steps:
      - name: Print workflow_run.event
        run: echo ${{ github.event.workflow_run.event }}
      - name: Print pull_request.merged
        run: echo ${{ github.event.workflow_run.pull_requests[0].merged }}
      - name: Print workflow_run
        run: echo ${{ github.event.workflow_run }}
